//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.3

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "douyin_qrcode")]
pub struct Model {
    pub qrcode_data: Option<String>,
    pub qrcode_url: Option<String>,
    pub create_time: Date,
    pub update_time: Date,
    pub status: i16,
    pub is_using: i16,
    pub invalid: i16,
    #[sea_orm(primary_key)]
    pub tid: i64,
    pub uid: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
