//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.3

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "douyin_task")]
pub struct Model {
    pub create_time: Date,
    pub update_time: Date,
    pub status: i16,
    pub dyid: String,
    pub task: String,
    #[sea_orm(primary_key)]
    pub tid: i64,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
