//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.3

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "douyin_announce")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub tid: i64,
    pub r#type: i32,
    pub marked: i32,
    pub title: String,
    #[sea_orm(column_type = "JsonBinary")]
    pub info: Json,
    #[sea_orm(column_type = "JsonBinary")]
    pub content: Json,
    pub update_time: DateTimeWithTimeZone,
    pub create_time: DateTimeWithTimeZone,
    pub status: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
