//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.3

pub mod prelude;

pub mod douyin_announce;
pub mod douyin_browser;
pub mod douyin_config;
pub mod douyin_like;
pub mod douyin_object;
pub mod douyin_qrcode;
pub mod douyin_task;
pub mod douyin_version_object;
pub mod user;
