//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.3

pub use super::douyin_announce::Entity as DouyinAnnounce;
pub use super::douyin_browser::Entity as DouyinBrowser;
pub use super::douyin_config::Entity as DouyinConfig;
pub use super::douyin_like::Entity as DouyinLike;
pub use super::douyin_object::Entity as DouyinObject;
pub use super::douyin_qrcode::Entity as DouyinQrcode;
pub use super::douyin_task::Entity as DouyinTask;
pub use super::douyin_version_object::Entity as DouyinVersionObject;
pub use super::user::Entity as User;
